sudo: required
services:
  - docker

before_install:
  - docker build -t satishbonam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true satishbonam/react-test npm run test

language: generic

after_success:
  - docker build -t satishbonam/multi-client ./client
  - docker build -t satishbonam/multi-nginx ./nginx
  - docker build -t satishbonam/multi-server ./server
  - docker build -t satishbonam/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push to docker hub
  - docker push satishbonam/multi-client
  - docker push satishbonam/multi-nginx
  - docker push satishbonam/multi-server
  - docker push satishbonam/multi-worker
