sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t satishbonam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true satishbonam/react-test npm test

after_success:
  - docker build -t satishbonam/multi-client ./client
  - docker build -t satishbonam/multi-nginx ./nginx
  - docker build -t satishbonam/multi-server ./server
  - docker build -t satishbonam/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push satishbonam/multi-client
  - docker push satishbonam/multi-nginx
  - docker push satishbonam/multi-server
  - docker push satishbonam/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-058586967339"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
